apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wpsecret.name }}
  namespace: {{ .Values.namespace1 }}
type: {{ .Values.secret_type }}
data:
  password: {{ .Values.wpsecret.data.firstkey.value }}