apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysqlsecret.name }}
  namespace: {{ .Values.namespace2 }}
type: {{ .Values.secret_type }}
data:
  password: {{ .Values.mysqlsecret.data.firstkey.value }}